apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: btc
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=  # "password" encodé en base64
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-endpoint
  namespace: btc
type: Opaque
data:
  database: YnRjX2Ri  # "btc_db" encodé en base64
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-user-pass
  namespace: btc
type: Opaque
data:
  username: dXNlcg==  # "user" encodé en base64
  password: cGFzc3dvcmQ=  # "password" encodé en base64